sudo: true
language: ruby
services:
    - docker
cache: bundler
rvm:
- 2.2.3

script:
  - bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}
  - bundle exec rake
  - docker build -t datarator/datarator:edge .
  - ./scripts/travis/docker_test_run.sh

after_success:
  # for tagged releases => deploy latest + tag versions as well
  - if [[ ! -z "$TRAVIS_TAG" ]]; then docker tag datarator/datarator:edge datarator/datarator:latest && docker tag datarator/datarator:edge datarator/datarator:$TRAVIS_TAG ; fi
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push datarator/datarator

deploy:
  - provider: rubygems
    api_key:
      secure: LncHjVlmOdTD13/1Ba0uKFMguum4l/GqoIBLdFON/1h+NEbQ+TfMfqGVjTHN+XTA3sBmukwHeNK8DRuYcenlkmJeyNayDxvyodTf3hSxPFY9NviG6lH8GWpshru0IpQ1YAiHBnzG8bFxVK17ZsE9LuUBYqCytsjcVSBghXAHgvU=
    gem: datarator
    on:
      tags: true
      repo: datarator/datarator
  - provider: heroku
    api_key:
      secure: fslycBnFpNvJ6Qh3YavkoxENdkieqvrowjw5bE1tmsUSyYN00b6TKx+osm3Ai1WzJTJ+AyU6wTVi2vKHKMi+bF0wujUXouzHhMmjmw5RuiJTKmVD7Oc7lSBSIPRb2e+MAwa+UhkzC+qU/jl3oOJBtggmAymFw08BopHUfs1i93M=
    app: datarator
    on:
      tags: true
      repo: datarator/datarator
