language: ruby
cache: bundler
rvm:
- 2.0.0
env:
  matrix:
    - JOB=rest
    - JOB=ui CHROME_BIN="chromium-browser" DISPLAY=":99.0"
before_install:
  - if [[ $JOB == *ui* ]]; then sh -e /etc/init.d/xvfb start; fi
  - if [[ $JOB == *ui* ]]; then pushd ui; fi
  - if [[ $JOB == *ui* ]]; then npm install -g bower grunt-cli protractor grunt-protractor-runner; fi
install:
  - if [[ $JOB == *ui* ]]; then bower install; fi
  - if [[ $JOB == *ui* ]]; then npm install; fi
  - if [[ $JOB == *rest* ]]; then bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}; fi # took over the travis defaults, see: https://travis-ci.org/datarator/datarator/builds/42351889
before_script:
  - if [[ $JOB == *ui* ]]; then bundle exec rackup -D; fi
  # till we can start backend and frontend via one command, let's use the way used in manual tests as well
  - if [[ $JOB == *ui* ]]; then grunt spinup &; fi
  # TODO do we need to silence selenium? see: http://andrew.yurisich.com/work/2014/08/30/silence-noisy-selenium-server-output-in-travis-ci/
script:
  - if [[ $JOB == *ui* ]]; then npm test; fi
  - if [[ $JOB == *rest* ]]; then bundle exec rake; fi
deploy:
  - provider: rubygems
    api_key:
      secure: LncHjVlmOdTD13/1Ba0uKFMguum4l/GqoIBLdFON/1h+NEbQ+TfMfqGVjTHN+XTA3sBmukwHeNK8DRuYcenlkmJeyNayDxvyodTf3hSxPFY9NviG6lH8GWpshru0IpQ1YAiHBnzG8bFxVK17ZsE9LuUBYqCytsjcVSBghXAHgvU=
    gem: datarator
    on:
      tags: true
      repo: datarator/datarator
  - provider: heroku
    api_key:
      secure: fslycBnFpNvJ6Qh3YavkoxENdkieqvrowjw5bE1tmsUSyYN00b6TKx+osm3Ai1WzJTJ+AyU6wTVi2vKHKMi+bF0wujUXouzHhMmjmw5RuiJTKmVD7Oc7lSBSIPRb2e+MAwa+UhkzC+qU/jl3oOJBtggmAymFw08BopHUfs1i93M=
    app: datarator
    on:
      tags: true
      repo: datarator/datarator

